### ISSUE TITLE
Feature Request: Possibility of unifying all http endpoints

### ISSUE THREAD

**Issue by sachinwalia2k8** [h2non/imaginary#101]
Is it possible to unify all Http Endpoints under a single endpoint such as /process
based on input parameters it can internally call APIs such as watermarking, resizing etc.

thanks.

**Comment by h2non** [comment]
Yes, that should be easy.

**Comment by krazyjakee** [comment]
@h2non can you open a Patreon or something so I can financially incentivise this feature into existence?

**Comment by h2non** [comment]
@krazyjakee Thanks for the interest. Financial contributions are always welcome. All my open source work is free and without lucrative purpuses, but if people is taking some sort of sustantiable financial benefit of using them, donations are appreciated.

I just created a [Pantreon account](https://www.patreon.com/user?u=4882305), but you can also send money to my Paypal account (tomas <at> aparicio [dot] me).

**Comment by h2non** [comment]
@krazyjakee `imaginary` is not an Open Collective project. You can be a backer clicking here:
https://opencollective.com/imaginary#support

**Comment by krazyjakee** [comment]
@h2non great! thanks 👍

**Comment by h2non** [comment]
Awesome, really appreciated.

**Comment by h2non** [comment]
Considering introducing this feature in `v0.1.31`.

**Comment by h2non** [comment]
imaginary `v1.0.8` is out implementing this feature, via `/pipeline` endpoint.

For documentation and usage details, see:
https://github.com/h2non/imaginary#get--post-pipeline

For implementation details, see:
https://github.com/h2non/imaginary/commit/196410cbbc0199c36a4a7259f7f4dd15bfb333e0

[node-imaginary](https://github.com/h2non/node-imaginary) package also supports it from version `v0.1.13`. See the usage example here:
https://github.com/h2non/node-imaginary/blob/master/examples/pipeline.js
