### ISSUE TITLE
Conversion throwing Unsupported image output type

### ISSUE THREAD

**Issue by krazyjakee** [h2non/imaginary#105]
Example url: `http://127.0.0.1:8081/convert?type=webp&url=http://plancksconstant.org/blog1/iamges/dogfood.png`

Error: 
```
{
"message": "Error while processing the image: Unsupported image output type",
"code": 1
}
```

Installed:
- imaginary 0.1.28
- libvips 8.4.2
- bimg 1.0.5

Am I missing something?

**Comment by h2non** [comment]
Looks like `libvips` has not been compiled with proper `libwebp` bindings.

**Comment by krazyjakee** [comment]
Yup!

For anyone else on OSX

```
brew tap homebrew/science
brew install vips
brew install vips --with-cfitsio --with-fftw --with-imagemagick --with-libexif --with-liboil --with-libtiff --with-little-cms --with-openexr --with-openslide --with-pango
```

One of these includes webp support.

**Comment by haf** [comment]
Seems to be outdated;

` brew reinstall vips --with-imagemagick --with-openexr --with-openslide --with-webp`
