### ISSUE TITLE
How do I send the mount path to the docker image?

### ISSUE THREAD

**Issue by krazyjakee** [h2non/imaginary#106]
I'm running the docker image but am unable to set a mount path.

I've googled for hours but I just can't see how I can send arguments to the running image.

**Comment by h2non** [comment]
It's fairly simple:
```bash
docker run -p 9000:9000 -v /some/local/folder:/mnt -t h2non/imaginary -p 9000 -cors -concurrency 20 -enable-url-source -mount /mnt
```

That passes multiple flags to `imaginary` binary while running inside the Docker container. 
It also mounts a local directory as volume inside the container, so you can then load and process images from the file system, and then running requests like:
````bash
http://localhost:9000/crop?width=400&file=example.jpg
```
Where `example.jpg` is loaded from your local directory in `/some/local/folder/example.jpg`.

I hope this helps.
