### ISSUE TITLE
0.1.28 has cpu and memory usage issues

### ISSUE THREAD

**Issue by wirtsi** [h2non/imaginary#107]
Another rather hazy report from me:

After upgrading imaginary to 0.1.28, our kubernetes cluster works nicely for about 2h.

After that, the CPU and memory usage of imaginary goes through the roof. There are no messages logged. In the attached screenshot you can see the load times and how they recover after restarting all pods running imaginary.

The average response time isn't affected to badly but it appears there are stuck/bogged threads that completely kill the percentiles....

I reverted back to 0.1.27 and the problems are all good. 

So it appears that the new libvips library is leaking resources (just an inspired guess, i have no idea)

![bildschirmfoto 2016-11-03 um 18 07 24](https://cloud.githubusercontent.com/assets/276751/19976631/cbdfb510-a1f0-11e6-9e84-31256c1238a8.png)

**Comment by wirtsi** [comment]
This is after the rollback ... we are at around 80 req/s shared between 7 pods running on a 8 * 4 cores cluster (alongside with quite a few other pods)

<img width="628" alt="bildschirmfoto 2016-11-03 um 20 10 28" src="https://cloud.githubusercontent.com/assets/276751/19981282/9ce0f83a-a201-11e6-8340-022c4da58e35.png">

**Comment by h2non** [comment]
Thanks for sharing.

It is very possibly due to `libvips` upgrade in `0.1.28`. If you have some stats about resident memory, that would be helpful. 

Will do some tests, hopefully during the weekend. If the issue comes from `libvips`, I will downgrade the embedded version in the Docker image and make a new release of `imaginary`, until the issue can be mitigated in some way.

**Comment by wirtsi** [comment]
Hi ... 

sorry, I cannot provide you with any cool graphs regarding the memory usage. I can get it for individual nodes but I fail to cross reference if imaginary actually ran on them.

I do recall ssh'ing into a pod, top gave me a memory usage of 12 GB (virtual) and about  4 GB resident. That seems too much, currently I am bombing the system with around 300 req/s and an individual pod gives me

` 
PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
    1 root      20   0 2472228 453760  15536 S  53.6  3.0   2:19.30 imaginary
`

**Comment by claws-se** [comment]
Just to let you know, I think this problem persists in version 0.1.30 as well.

**Comment by h2non** [comment]
Can you reproduce the issue in the using the latest Docker image `v0.1.31`? Both `libvips` and `bimg` were upgraded.

**Comment by wirtsi** [comment]
Deploying to production now, fingers crossed ...

**Comment by wirtsi** [comment]
0.1.31 has been running for 2 days now. It seems to behave very well now ... I'll close this

**Comment by marcopeg** [comment]
Guys this is still an open issue in version 1.0.15, memory doesn't get released.

**Comment by badboyd** [comment]
I have met the same problem. Could you guys please check ?
