### ISSUE TITLE
Use of lovell/sharp/master/preinstall.sh is deprecated, will be removed at end of 2016

### ISSUE THREAD

**Issue by lovell** [h2non/imaginary#108]
Hello,

A quick [Github search](https://github.com/search?o=desc&q=https%3A%2F%2Fraw.githubusercontent.com%2Flovell%2Fsharp%2Fmaster%2Fpreinstall.sh&ref=searchresults&s=indexed&type=Code&utf8=%E2%9C%93) reveals this repo still contains at least one refence to the deprecated `preinstall.sh` script at https://raw.githubusercontent.com/lovell/sharp/master/preinstall.sh

At the end of 2016 this script will be removed and the URL will return a 404 status code.

sharp v0.12.0+ does not require the use of this script.

Please take and maintain a copy if still required by this repo.

Thank you for using libvips/sharp!

Cheers,
Lovell

**Comment by h2non** [comment]
Thank you for reporting this here.

**Comment by h2non** [comment]
Script ported! Closing.
