### ISSUE TITLE
Low quality output when resizing high dpi images

### ISSUE THREAD

**Issue by nvartolomei** [h2non/imaginary#109]
Resulting jpeg with 100% quality

![crop](https://cloud.githubusercontent.com/assets/543193/20143162/9569a8c4-a6a0-11e6-9dd5-6f3bad4592af.jpeg)
<img width="1393" alt="sh" src="https://cloud.githubusercontent.com/assets/543193/20143163/9569b3be-a6a0-11e6-93f8-3de52cfed786.png">

**Comment by h2non** [comment]
Duplicated in the `libvips` repository. Closing.
