### ISSUE TITLE
AWS S3 support

### ISSUE THREAD

**Issue by ychw** [h2non/imaginary#110]
Hi thanks for the great work. 

Dows imaginary support S3? If so, how do I configure? Also, what would be the structure of files saving to local disk? (folder structures, files / folder, etc.)

thanks

**Comment by h2non** [comment]
Imaginary is a read only service. It can only read images from multiple sources, but never wtitten them.

You can use the URL based image processing in order to process images stored in S3.

**Comment by ychw** [comment]
So it doesn't have upload function? For serving, is there a way to read from S3 directly?

**Comment by h2non** [comment]
Yes, you can run a POST request with you image against imaginary. Please, see the docs.

**Comment by h2non** [comment]
Question answered. Closing.
