### ISSUE TITLE
error: undefined reference to vips 

### ISSUE THREAD

**Issue by hieutrtr** [h2non/imaginary#121]
By following installation guide of imaginary and got those issues when run `go build`.
Do i need to set some ENV ?
/go/src/gopkg.in/h2non/bimg.v1/metadata.go:31: error: undefined reference to 'g_object_unref'
/go/src/gopkg.in/h2non/bimg.v1/metadata.go:37: error: undefined reference to 'vips_thread_shutdown'
/go/src/gopkg.in/h2non/bimg.v1/vips.h:142: error: undefined reference to 'vips_type_find'
/go/src/gopkg.in/h2non/bimg.v1/vips.h:121: error: undefined reference to 'vips_type_find'
/go/src/gopkg.in/h2non/bimg.v1/vips.h:124: error: undefined reference to 'vips_type_find'
/go/src/gopkg.in/h2non/bimg.v1/vips.h:127: error: undefined reference to 'vips_type_find'
/go/src/gopkg.in/h2non/bimg.v1/vips.h:200: error: undefined reference to 'vips_image_get_typeof'
/go/src/gopkg.in/h2non/bimg.v1/vips.h:201: error: undefined reference to 'vips_image_get_string'
/go/src/gopkg.in/h2non/bimg.v1/vips.h:210: error: undefined reference to 'vips_interpolate_new'
/go/src/gopkg.in/h2non/bimg.v1/vips.h:211: error: undefined reference to 'vips_interpolate_get_window_size'
/go/src/gopkg.in/h2non/bimg.v1/vips.h:212: error: undefined reference to 'g_object_unref'

I have libvips 8.4.2
```
curl -s https://raw.githubusercontent.com/h2non/bimg/master/preinstall.sh | sudo bash -
Found libvips 8.4.2
```

**Comment by h2non** [comment]
Looks like `libvips` C headers cannot be found in standard directories. Please, ensure you have the following environment variables properly declared:
```bash
export VIPSHOME=/path/to/libvips
export LD_LIBRARY_PATH=$VIPSHOME/lib:$LD_LIBRARY_PATH
```
and then try compiling it again.

For more information, see:
https://github.com/jcupitt/libvips/wiki/Install-to-private-prefix

**Comment by hieutrtr** [comment]
i found this can be fix by install new version of golang.
Thanks you.
