### ISSUE TITLE
Confused about crop vs. resize

### ISSUE THREAD

**Issue by crrobinson14** [h2non/imaginary#123]
I'm trying to scale and crop an image, while maintaining aspect ratio. In other stacks like this (e.g. Thumbor) this is done by simply specifying a width, and height is automatically calculated to maintain aspect ratio.

Imaginary doesn't seem to be doing this. Instead, if only width is supplied, it seems to crop the image to that width while maintaining the original height. In other words, if you take a 1024x768 image and ask for a width=320 crop, you get a 320x768 image. What would be the right parameters to get a 320x240 image, without actually knowing the original dimensions of the source?

**Comment by crrobinson14** [comment]
OK got this sorted out. Seems I needed to use the `thumbnail` endpoint instead. Suggestion: it would be good to clarify the purpose of these calls in the docs.

**Comment by RDGthree** [comment]
Just ran into this as well. For resize, the docs say:

> Resize an image by width or height. Image aspect ratio is maintained

Seems like the expected functionality is that the photo retains aspect ratio (and it seems to when the height is less than the width), but if only width is supplied as a parameter and height is greater than width, it crops.

**Comment by hauleth** [comment]
That is quite unclear. I would rather say that resize mean: "force given dimensions", crop: "cut part that has given dimensions" and thumbnail: "resize image, keeping ratio, to fit into given dimensions". Now it is somewhat messed up.
