### ISSUE TITLE
How send the information with POST

### ISSUE THREAD

**Issue by EricRSuarez** [h2non/imaginary#130]
Hi, I have been use your app and I try to render images with POST. I make a POST and I get an error.

Example:

I execute:   imaginary -p 80  -enable-url-source
I do a get request with http://40.114.246.191:8080/crop?width=300&height=300&url=https://raw.githubusercontent.com/h2non/imaginary/master/fixtures/large.jpg and imaginary render the img perfectly

but when I try with post with form-url-encoded

http://40.114.246.191:8080/crop

Payload:
width=300&height=300&url='https://raw.githubusercontent.com/h2non/imaginary/master/fixtures/large.jpg'

I got a error message 

{
message: "Unsupported media type"
code: 3
}

I also try with a json 

{
  "width"=300,
  "height"=300,
  "url"='https://raw.githubusercontent.com/h2non/imaginary/master/fixtures/large.jpg'
}

but a get the same error

Can you help me? 
Thanks a lot. Imaginary is awesome

**Comment by tomas-fp** [comment]
Why do you want to send a POST request? If you want to process an image that is accessible via public URL, you should just do a GET request specifying the image URL via `url` query param, as you did in your first example.

If you want to process an custom image that is not URL accessible, then you should perform a POST request providing the image binary content as payload as `application/octet-stream`or via `multipart/form` with a field called `file`.

See documentation for more details:
https://github.com/h2non/imaginary#form-data

**Comment by Dynom** [comment]
In addition to what @tomas-fp said: The parameters go in the URL and the image goes in the body. Take a look at the `/form` action to see how it works there.

There is currently no way (that I know of) to send the URL parameter in the body of a POST request. Post is needed if you want to send the contents of the file (binary data) to Imaginary for processing.

If you have no further questions about this topic, feel free to close the issue.

**Comment by h2non** [comment]
Closing issue.
