### ISSUE TITLE
Crop & Resize do the same thing ?

### ISSUE THREAD

**Issue by JeanMarieAries** [h2non/imaginary#132]
Hello

I'm going to find a new resize system for my company, and i currently test 'imaginary'. I don't know if it's a setup issue, but /crop & /resize do the same thing (it make a crop). Is it an issue or a normal state that i don't understand ?
Thanks in advance for your help

PS : I think this problem appear with the enable-url-source flag, and a remote image. no problem with the /form page and the examples

**Comment by Dynom** [comment]
With `/resize` you can specify `..&nocrop=true` to prevent cropping. Without that, the behaviour is very similar to `/crop`.

See also: https://github.com/h2non/imaginary#params

**Comment by h2non** [comment]
Closing.
