### ISSUE TITLE
Use libvips compiled with gif support

### ISSUE THREAD

**Issue by benone** [h2non/imaginary#137]
Hi!

How can I use libvips with libgif?
I should compile libvips/bimg manually after install libgif?

Thanks.

**Comment by h2non** [comment]
From `libvips@v8.3+` you have optional and transparent GIF support if compiled with proper library binding. For instance, `imaginary` Docker image is shipped with latest `libvips` and GIF support.

**Comment by titpetric** [comment]
I think this would need to be reopened, I'm getting the following error with the latest imaginary docker image:

```
{"message":"Error while processing the image: VIPS cannot save to \"gif\"","code":1}
```

request is like this:

```
172.25.0.4 - - [15/Nov/2017 10:27:56] "GET /resize?file=_up/upload/2017/11/13/test.gif&height=210&extend=background&background=255,255,255&nocrop=true HTTP/1.0" 400 84 0.0671
```

```
h2non/imaginary                            latest              5e31897ac085        34 hours ago        1.169 GB
```

**Comment by titpetric** [comment]
Already found out that [saving to gif is unsupported](https://github.com/h2non/bimg/blob/master/vips.go#L198). :(

**Comment by VengefulAncient** [comment]
Sorry for commenting on an old thread, but this is the only reference to this error I've found - what exactly is a "save operation" in Imaginary? I got the above error when trying to simply resize a GIF (no other operations). Is that not supported?
