### ISSUE TITLE
Convert with crop disabled

### ISSUE THREAD

**Issue by geekrohit** [h2non/imaginary#142]
Hi,

Currently am trying to convert and resize using the convert api endpoint. However, passing nocrop=true and extend parameter has no effect on the end result, unlike the resize endpoint.

Any ideas? I've tried added opts.Crop = false in the convert function but to no avail.

**Comment by h2non** [comment]
Just use resize endpoint explicitly passing the conversion format you want. It should work.

**Comment by geekrohit** [comment]
Works 👍  Thanks.
