### ISSUE TITLE
Max allowed size option broken

### ISSUE THREAD

**Issue by eseliger** [h2non/imaginary#146]
Setting the `-max-allowed-size` option to some value (anything, greater than 0) causes an error for url-based image access all the time.

**Sample to reproduce**
Start params: `docker run -p 9000:9000 h2non/imaginary -enable-url-source -max-allowed-size 1`
Open: `http://localhost:9000/crop?url=http://my-u.rl/img&width=500`
returns: `{"message":"Error fetching image http headers: (status=200) (url=http://my-u.rl/img)","code":1}`

Digging into it shortly, it seems an if-condition is probably wrong. https://github.com/h2non/imaginary/blob/master/source_http.go#L45 It should be an error for every status code except from the range 200..206, not vice versa, as it is now.

**Comment by tomas-fp** [comment]
This should be fixed in `imaginary@v1.0.2`. Docker image will be available soon, but you can upgrade it by running: `go get -u github.com/h2non/imaginary`

**Comment by h2non** [comment]
Fixed. Closing.
