### ISSUE TITLE
Option to disable form path

### ISSUE THREAD

**Issue by kureikain** [h2non/imaginary#156]
It's really dangerous to expose `form` path. We can argue about making this upstream to deny access to this route. However, given that selling point of Go is easy to deployment, without putting it behind another load balancer, I think a simple option to disable `form` route is quite useful.

I can work on this feature since I need it badly. Just not sure if this feature can be merged?

**Comment by h2non** [comment]
I don't understand why you see that endpoint dangerous, but I also don't see why it cannot be optionally disabled. PR are welcome.

**Comment by Dynom** [comment]
You could use https://github.com/Dynom/proxima if you can't wait and/or are not able to provide a PR.

If you have Imaginary running on the same host as Proxima, you can do the following:

```sh
./imaginary -a 127.0.0.1 -p 9001 -enable-url-source
```
And
```sh
./proxima --allowed-actions="info,crop,resize,<add more actions you want to allow>" --imaginary-url="http://127.0.0.1:9001" --listen-port=9000
```

Proxima shares some hardening features with Imaginary and we should perhaps integrate some of Proxima's features in Imaginary, but this'll work as a quick fix.

**Comment by h2non** [comment]
Implemented. See: #160
