### ISSUE TITLE
Content-Length mismatch when enable gzip

### ISSUE THREAD

**Issue by xuqingfeng** [h2non/imaginary#157]
```
docker run -d --name imaginary -p 9000:9000 -v `pwd`/data:/data h2non/imaginary -cors -enable-url-source -gzip -mount /data

open http://127.0.0.1:9000/resize?width=1000&height=1000&file=test.png
```
chrome throw `Failed to load resource: net::ERR_CONTENT_LENGTH_MISMATCH`

It's most likely caused by the gzip lib you are using. Found a possible [fix](https://github.com/daaku/go.httpgzip/pull/7) but the author doesn't seem to want to fix that.

Ref: https://github.com/golang/go/issues/14975

**Comment by h2non** [comment]
Thanks for reporting this. It looks like `httpgzip` package is no longer maintained. My suggestion would be embeddeding its code within `imaginary`, since the code base is small, and them implement there the fix.

PR are welcome :)

**Comment by Dynom** [comment]
Just out of curiosity, how much does the gzip compression add to the images? I've considered it a rather expensive feature for my use-cases, because of nature of images used for web and the costs for compression.

This is by no means intended as critic, I'm honestly curious about the gains.

**Comment by h2non** [comment]
Generally speaking, it would not add too much benefits, actually just the opposite (because of unnecessary CPU bound processing). I suspect only in a small percentadge of images would have some benefits after gzipping them.

**Comment by Dynom** [comment]
If there isn't a big incentive, we could strip the feature out instead?

**Comment by h2non** [comment]
That sounds reasonable. That could happen in the next version, possibly.

**Comment by h2non** [comment]
Done in `v1.0.9`. `-gzip` flag will show a warning message via `stdout`. Closing.

**Comment by kureikain** [comment]
wow, I was got hit by this and thinking that due to double gzip(gzip in imaginary then gzip in my load balancer). Didn't know it's an bug in httpgzip. THanks again
