### ISSUE TITLE
throttled has changed package location

### ISSUE THREAD

**Issue by 11bit** [h2non/imaginary#158]
When I try to `go get -u github.com/h2non/imaginary` I am getting the following error:

```
package gopkg.in/throttled/throttled.v2: code in directory ~/go/src/gopkg.in/throttled/throttled.v2 expects import "github.com/throttled/throttled"
package gopkg.in/throttled/throttled.v2/store/memstore: code in directory ~/go/src/gopkg.in/throttled/throttled.v2/store/memstore expects import "github.com/throttled/throttled/store/memstore"
```

Looks like they have changed package location

**Comment by Dynom** [comment]
@h2non we should just switch to vendored packages imo, how do you feel about that?

**Comment by h2non** [comment]
Totally, this is something I wanted to support for a while.

**Comment by h2non** [comment]
Vendor dependencies is now supported using official `dep` tool.
