### ISSUE TITLE
Unsupported Media Type for PNGs

### ISSUE THREAD

**Issue by CentaurWarchief** [h2non/imaginary#179]
I am getting:

```JSON
{"message": "Unsupported media type", "code": 3}
```

for this URL: https://cdn.filestackcontent.com/567NqIvTfynHsYQB0Zhx. Not really sure what's the issue. Maybe the mime detector isn't detecting it as a PNG. Your thoughts?

**Comment by h2non** [comment]
That's an ICO file format.

**Comment by CentaurWarchief** [comment]
Wow — thanks @h2non, didn't notice that
