### ISSUE TITLE
Resized image off by 1px

### ISSUE THREAD

**Issue by thenrikie** [h2non/imaginary#180]
This is the URL I used to resize an imag:
/resize?width=460&type=png&nocrop=true&file=[filename]

The output image looks good to me initially, but when I try to compare
it side by side with other solutions (photoshop and imgix.com), it looks like the image
resized by imaginary is off by 1px.

Here is one example:
Photoshop:
https://s3.eu-west-2.amazonaws.com/test-imgs-resize/photoshop_5.png

Imgix:
https://s3.eu-west-2.amazonaws.com/test-imgs-resize/imgix_5.png

imaginary:
https://s3.eu-west-2.amazonaws.com/test-imgs-resize/imaginary_5.png

I am not sure if it is the intended resize effect or I called the URL with wrong parameters?

**Comment by Dynom** [comment]
You're right, there is a slight difference between the imaginary image and the other two. However I'm curious what the cause is, it seems that Photoshop and Imgix don't really start at [0, 0]?

**Comment by Dynom** [comment]
Possibly related: https://github.com/h2non/imaginary/issues/180

**Comment by thenrikie** [comment]
Not anymore. Thanks.
