### ISSUE TITLE
Breaking for https urls

### ISSUE THREAD

**Issue by jstubenrauch** [h2non/imaginary#185]
Hi,

I am getting the following error for every request!

`{"message":"Error downloading image: Get https://***/images/1281547: x509: failed to load system roots and no roots provided","code":1}`

[This Article](http://blog.cloud66.com/x509-error-when-using-https-inside-a-docker-container/) explains how to solve the issue.

Thanks!

**Comment by jstubenrauch** [comment]
#186 should fix the issue

**Comment by h2non** [comment]
Merged. New Docker release will be available in the registry soon. Thank you.

**Comment by samuelchiang** [comment]
The docker image in dockerhub is not well-built. Util I enter the bash and doing the following instructions manually.

docker exec -ti <docker_name> bash
apt-get update && apt-get install -y ca-certificates
docker restart <docker_name>

Then it works.

**Comment by h2non** [comment]
`v1.0.15` is out, including its Docker image with the fix.
