### ISSUE TITLE
Any plans to support HEIC format?

### ISSUE THREAD

**Issue by ldadams** [h2non/imaginary#187]

**Comment by Dynom** [comment]
I think people are treading lightly around HEIC due to the patents. However Imaginary (and bimg) use libvips under it's hood, if libvips supports it, we won't be too far behind.

The thread to follow is: https://github.com/jcupitt/libvips/issues/671

**Comment by jcupitt** [comment]
Hello, libvips 8.8 has HEIC support. As you say, there are a range of patents issues and you do need to be careful :(

**Comment by vposhamod** [comment]
Not sure if this is complaint or not. But imgproxy added with https://github.com/imgproxy/imgproxy/pull/179/files and looks like they also have a MIT license

**Comment by DanielDent** [comment]
You may wish to test the build I've created: https://github.com/h2non/imaginary/pull/297

**Comment by vposhamod** [comment]
Cool, I tested with my samples and it works. 👍 

However, as @jcupitt mentioned - not sure about licensing around it.

**Comment by h2non** [comment]
Feature shipped in `v1.2.0`.
