### ISSUE TITLE
running docker image on mac os x has an issue with certificates

### ISSUE THREAD

**Issue by evrenkutar** [h2non/imaginary#188]
Hi, this was the error I got 
```{"message":"Error downloading image: Get https://somedomain.some/someimage.jpg: x509: failed to load system roots and no roots provided","code":1}```

I fixed it mounting the certs volume, adding these lines to docker-compose.yml file
```
imaginary:
        volumes:
            - /etc/ssl/certs:/etc/ssl/certs
```

I think this will help if this to be in troubleshooting guide - readme or somewhere.

Thanks a lot

**Comment by Dynom** [comment]
I think this is fixed with the merge of https://github.com/h2non/imaginary/pull/186 and should be available on [h2non/imaginary:1.0.14](https://hub.docker.com/r/h2non/imaginary/tags/)

**Comment by Dynom** [comment]
Maybe I spoke too soon. I'm having troubles with this version as well, I think you've found a bug!

**Comment by evrenkutar** [comment]
i don't know if it helps but here is my pr #190
tried locally, it is working, sorry for no tests at all in the pr.

**Comment by Dynom** [comment]
I've actually just added PR #189 with the fix for your specific problem. I'm not aware of any problems related to Java?

**Comment by evrenkutar** [comment]
you're right. pr closed. #189  +1

**Comment by h2non** [comment]
`v1.0.15` is out, including its Docker image with the fix.
