### ISSUE TITLE
Is the image on Docker Hub built with race detector?

### ISSUE THREAD

**Issue by arthow4n** [h2non/imaginary#196]
Just wondering is there a specific reason to enable race detector (`go build -race`) in the docker image, or is the image on Docker Hub built with it?
https://github.com/h2non/imaginary/blob/d11fb053f19aefe5049b4e85b74163e88c3c966a/Dockerfile#L72

According to Go [docs](https://golang.org/doc/articles/race_detector.html#Runtime_Overheads), there is a significant runtime overhead by enabling the race detector. The image used in production should not be built with it.

**Comment by h2non** [comment]
I'm afraid your are right. I don't recall why or for what that flag has been placed there.

**Comment by arthow4n** [comment]
I opened a companion PR, hope it helps!

**Comment by h2non** [comment]
Fixed. A new version will be released soon. Thank you.
