### ISSUE TITLE
Can I get the url for the original size(unprocessed image) image?

### ISSUE THREAD

**Issue by fengchangfight** [h2non/imaginary#213]
the http api looks like /fit?*** , /rize?***, that looks cool, but is there anyway I can just get the original size image url?

**Comment by h2non** [comment]
See: https://github.com/h2non/imaginary#get--post-info

**Comment by fengchangfight** [comment]
No no , that only return the metadata, not the image itself @h2non

**Comment by h2non** [comment]
No. The image is provided by the client somehow, whether if it's a remote image or an uploaded image. `imaginary` does not store any image after processing it.

**Comment by fengchangfight** [comment]
but there is a -mount option right? for using local images,  when we specify file=***, I think it would be great to make use of that, kind of equal to using the /fit api with an unlimited bound

**Comment by fengchangfight** [comment]
thanks @Dynom  and @h2non for your clarification~
