### ISSUE TITLE
Possibility of watermarking using an image!?

### ISSUE THREAD

**Issue by foobargeez** [h2non/imaginary#214]
The same question was asked last year and the answer was no. I am wondering if something changed and if there is a possibility of watermarking using an image (highly desired).

Thanks!

**Comment by h2non** [comment]
`bimg` supports it, so it's just a matter of providing HTTP API support in `imaginary`. The `/watermark` endpoint could, as ideas, read the image from a remote URL or a base64 encoded string (this has some limitations).

**Comment by foobargeez** [comment]
It will also be nice to support reading from fs path if `imaginary` is started with `-mount`.

@h2non, just to help plan my project timelines, would you be interested and/or have time to take up this enhancement?  If so, any tentative timeline?  If not, I will dig up the code -- not a gopher (yet) but I love `imaginary` for the exact reason that it is language agnostic given its built-in HTTP server.

Would appreciate if you can post the next steps either way.

**Comment by h2non** [comment]
I can't invest time working on `imaginary` at this very moment.

I'd suggest implementing it by yourself if you have time pressure.

You can start implementing the feature by:
1) Support a new query param that defines the remote or local watermark image source. E.g: `?watermark-image=https://server.com/image.jpg` (remote URL) or `?watermark-image=image.jpg` (local mounted directory).
2) Implement logic and validation to retrieve the image. This can be done at generic level via middleware.

**Comment by leonkunert** [comment]
Closed by #221?
