### ISSUE TITLE
does it support gif animation?

### ISSUE THREAD

**Issue by fengchangfight** [h2non/imaginary#215]
does it support gif animation?

**Comment by h2non** [comment]
It can read `gif` images, but can't produce them.

**Comment by antoniomo** [comment]
Can we reopen? https://github.com/libvips/libvips/issues/1167 and maybe https://github.com/h2non/bimg/pull/285

**Comment by patricknelson** [comment]
Just confirming (researching image proxy options): Does this support processing animated `gif` now?
