### ISSUE TITLE
Imaginary documentation is outdated

### ISSUE THREAD

**Issue by Lord-Y** [h2non/imaginary#217]
Hi docker image failed to start with with these parameters:

`URL_SIGNATURE_KEY=4f46feebafc4b5e988f131c4ff8b5997 docker run -d h2non/imaginary:latest -p 8080 -enable-url-signature` or with `
docker run -d h2non/imaginary:latest -p 8080 -enable-url-signature -url-signature-key 4f46feebafc4b5e988f131c4ff8b5997`
After checking the logs we can see the real requirements:
`# docker logs 5383bc76d2eb
flag provided but not defined: -enable-url-signature
imaginary 1.0.15

Usage:
  imaginary -p 80
  imaginary -cors
  imaginary -concurrency 10
  imaginary -path-prefix /api/v1
  imaginary -enable-url-source
  imaginary -disable-endpoints form,health,crop,rotate
  imaginary -enable-url-source -allowed-origins http://localhost,http://server.com
  imaginary -enable-url-source -enable-auth-forwarding
  imaginary -enable-url-source -authorization "Basic AwDJdL2DbwrD=="
  imaginary -enable-placeholder
  imaginary -enable-url-source -placeholder ./placeholder.jpg
  imaginary -h | -help
  imaginary -v | -version

Options:
  -a <addr>                 Bind address [default: *]
  -p <port>                 Bind port [default: 8088]
  -h, -help                 Show help
  -v, -version              Show version
  -path-prefix <value>      Url path prefix to listen to [default: "/"]
  -cors                     Enable CORS support [default: false]
  -gzip                     Enable gzip compression (deprecated) [default: false]
  -disable-endpoints        Comma separated endpoints to disable. E.g: form,crop,rotate,health [default: ""]
  -key <key>                Define API key for authorization
  -mount <path>             Mount server local directory
  -http-cache-ttl <num>     The TTL in seconds. Adds caching headers to locally served files.
  -http-read-timeout <num>  HTTP read timeout in seconds [default: 30]
  -http-write-timeout <num> HTTP write timeout in seconds [default: 30]
  -enable-url-source        Restrict remote image source processing to certain origins (separated by commas)
  -enable-placeholder       Enable image response placeholder to be used in case of error [default: false]
  -enable-auth-forwarding   Forwards X-Forward-Authorization or Authorization header to the image source server. -enable-url-source flag must be defined. Tip: secure your server from public access to prevent attack vectors
  -allowed-origins <urls>   Restrict remote image source processing to certain origins (separated by commas)
  -max-allowed-size <bytes> Restrict maximum size of http image source (in bytes)
  -certfile <path>          TLS certificate file path
  -keyfile <path>           TLS private key file path
  -authorization <value>    Defines a constant Authorization header value passed to all the image source servers. -enable-url-source flag must be defined. This overwrites authorization headers forwarding behavior via X-Forward-Authorization
  -placeholder <path>       Image path to image custom placeholder to be used in case of error. Recommended minimum image size is: 1200x1200
  -concurrency <num>        Throttle concurrency limit per second [default: disabled]
  -burst <num>              Throttle burst max cache size [default: 100]
  -mrelease <num>           OS memory release interval in seconds [default: 30]
  -cpus <num>               Number of used cpu cores.
                            (default for current machine is 6 cores)`

even with `-enable-auth-forwarding` param

**Comment by Dynom** [comment]
Hi!

Just to clear things up: `-enable-auth-forwarding` has nothing todo with the URL signature feature.

Furthermore:
The documentation isn't "outdated", it's in line with the current HEAD, which hasn't been released yet, to be slightly more specific, these rev's aren't released yet:
```
6887bcc Changing build steps (#189)
d11fb05 feat(version): bump to v1.0.15
3a3bd3a fix(docker): remove race detector (#197)
2a37482 Add URL signature feature (#194)
d48f428 Drop salt as suggested in #194 (#200)
e558c55 Fix typo in documentation (#202)
2a17cdf (upstream/master, origin/master, origin/HEAD, master) Update README.md (#207)
78f6096 Fixing typo
bd5a650 Adding wildcard support for allowing domains, closes #218
e47bc34 (HEAD -> AddingRemoteURLWildcardSupport, origin/AddingRemoteURLWildcardSupport) Updated the documentation
```

So either: Build your own Docker image from `master` or wait until v1.0.16 is released. :-)

If you want to know what your Docker image actually supports, try something like:
```
docker run --rm -it h2non/imaginary:v1.0.15 -h
```
