### ISSUE TITLE
Create a new release

### ISSUE THREAD

**Issue by philhug** [h2non/imaginary#224]
Please create a new release with the latest url signing functionality.

**Comment by onmomo** [comment]
and for the wildcard `-allowed-origins https://*.example.com` functionality

**Comment by Dynom** [comment]
I've just created the tag v1.0.15, however I don't have permission to update the image on Docker hub. You can, however, now build Imaginary yourself:

```sh
$ VERSION=v1.0.15 make docker-build
[..]
Successfully built dc842750bdeb
Successfully tagged h2non/imaginary:v1.0.15
```
