### ISSUE TITLE
blurred image when webp image gets shrinked

### ISSUE THREAD

**Issue by yuecelm** [h2non/imaginary#240]
suspect a bug in shrinkonload function with webp: https://github.com/h2non/bimg/issues/220

original file
![original](https://user-images.githubusercontent.com/12153500/51439479-fc115580-1cba-11e9-86d6-b42739af4977.jpg)

after `/fit?file=original.webp&height=250&width=250&type=jpeg`
![fit](https://user-images.githubusercontent.com/12153500/51439492-32e76b80-1cbb-11e9-83e2-1afa8dd05541.jpg)

also same problem when using `type=webp`

I converted here my images to jpg because webp not supported in github, but webp files are available zipped:
[webp.zip](https://github.com/h2non/imaginary/files/2776600/webp.zip)

**Comment by yuecelm** [comment]
workaround available:
`/pipeline?file=original.webp&operations=[{"operation":"convert","params":{"type":"jpeg"}},{"operation":"fit","params":{"height":500,"width":500,"type":"jpeg"}}]`

**Comment by yuecelm** [comment]
can somehow exclude a bug in libvips:
```
$ vips --vips-version
libvips 8.4.5-Wed Jan 18 12:36:44 UTC 2017
$ vipsthumbnail original.webp -s 250x188 -o tn_%s.webp --vips-cache-trace
vips cache+: webpload filename="original.webp" out=((VipsImage*) 0x5590a2d951a0) flags=((VipsForeignFlags) VIPS_FOREIGN_NONE) -
vips cache+: webpload filename="original.webp" out=((VipsImage*) 0x5590a2d95330) flags=((VipsForeignFlags) VIPS_FOREIGN_NONE) access=((VipsAccess) VIPS_ACCESS_SEQUENTIAL) shrink=4 -
vips cache+: colourspace in=((VipsImage*) 0x5590a2d95330) out=((VipsImage*) 0x5590a2d954c0) space=((VipsInterpretation) VIPS_INTERPRETATION_sRGB) -
vips cache : copy in=((VipsImage*) 0x5590a2d954c0) out=((VipsImage*) 0x5590a2d95970) -
vips cache+: black out=((VipsImage*) 0x5590a2d95e20) width=1 height=1 bands=3 -
vips cache : copy in=((VipsImage*) 0x5590a2d95e20) out=((VipsImage*) 0x5590a2e4d190) -
vips cache+: linear in=((VipsImage*) 0x5590a2d95e20) out=((VipsImage*) 0x5590a2e4d000) a=1  b=0  -
vips cache : copy in=((VipsImage*) 0x5590a2e4d000) out=((VipsImage*) 0x5590a2e4d4b0) -
vips cache+: cast in=((VipsImage*) 0x5590a2e4d000) out=((VipsImage*) 0x5590a2e4d320) format=((VipsBandFormat) VIPS_FORMAT_UCHAR) -
vips cache : copy in=((VipsImage*) 0x5590a2e4d320) out=((VipsImage*) 0x5590a2e4d640) -
vips cache+: embed in=((VipsImage*) 0x5590a2d95970) out=((VipsImage*) 0x5590a2d95b00) x=0 y=2 width=256 height=200 extend=((VipsExtend) VIPS_EXTEND_COPY) -
vips cache+: reducev in=((VipsImage*) 0x5590a2d954c0) out=((VipsImage*) 0x5590a2d957e0) vshrink=1.026596 kernel=((VipsKernel) VIPS_KERNEL_LANCZOS3) centre=TRUE -
vips cache : copy in=((VipsImage*) 0x5590a2d957e0) out=((VipsImage*) 0x5590a2e4d7d0) -
vips cache*: black width=1 height=1 bands=3 -
vips cache : copy in=((VipsImage*) 0x5590a2d95e20) out=((VipsImage*) 0x5590a2e4dc80) -
vips cache+: linear in=((VipsImage*) 0x5590a2d95e20) out=((VipsImage*) 0x5590a2e4daf0) a=1  b=0  -
vips cache : copy in=((VipsImage*) 0x5590a2e4daf0) out=((VipsImage*) 0x5590a2e7c000) -
vips cache+: cast in=((VipsImage*) 0x5590a2e4daf0) out=((VipsImage*) 0x5590a2e4de10) format=((VipsBandFormat) VIPS_FORMAT_UCHAR) -
vips cache : copy in=((VipsImage*) 0x5590a2e4de10) out=((VipsImage*) 0x5590a2e7c190) -
vips cache+: embed in=((VipsImage*) 0x5590a2e4d7d0) out=((VipsImage*) 0x5590a2e4d640) x=2 y=0 width=263 height=188 extend=((VipsExtend) VIPS_EXTEND_COPY) -
vips cache+: reduceh in=((VipsImage*) 0x5590a2d957e0) out=((VipsImage*) 0x5590a2d95c90) kernel=((VipsKernel) VIPS_KERNEL_LANCZOS3) hshrink=1.026596 centre=TRUE -
vips cache+: resize in=((VipsImage*) 0x5590a2d954c0) out=((VipsImage*) 0x5590a2d95650) centre=TRUE scale=0.974093 -
vips cache+: colourspace in=((VipsImage*) 0x5590a2d95650) out=((VipsImage*) 0x5590a2e7c4b0) space=((VipsInterpretation) VIPS_INTERPRETATION_sRGB) -
vips cache+: cast in=((VipsImage*) 0x5590a2e7c4b0) out=((VipsImage*) 0x5590a2e4d960) format=((VipsBandFormat) VIPS_FORMAT_UCHAR) -
vips cache : jpegsave in=((VipsImage*) 0x5590a2d95650) filename="./tn_original.jpg" -
```
it seems to use the shrinkonload function with shrink=4, but the results seems fine:
![tn_original](https://user-images.githubusercontent.com/12153500/51439610-3ed42d00-1cbd-11e9-8457-32f9ca6a1a4c.jpg)

**Comment by yuecelm** [comment]
500x500 -> not using shrink at all (should be 2)
300x300 -> shrink=2 (should be 3, if supported by webp, otherwise 2)
250x250 -> shrink=3 (should be 4)
200x200 -> shrink=3 (should be 5, if supported by webp, otherwise 4)
100x100 -> shrink=7 (should be 10, if supported by webp, otherwise 8)

**Comment by yuecelm** [comment]
https://github.com/libvips/libvips/wiki/HOWTO----Image-shrinking

**Comment by yuecelm** [comment]
above howto seems not be be up-to-date anymore: vipsthumbnail uses vips_thumbnail internally but it uses the max shrink factor (without the 2x headroom)

**Comment by yuecelm** [comment]
@Dynom @h2non how about using https://jcupitt.github.io/libvips/API/current/libvips-resample.html#vips-thumbnail directly (like done with vipsthumbnail)? We could add first this function to bimg and then use this function here. vips_thumbnail supports down-/upscaling, autorotate, crop and even supports linear light colorspace if needed. I also think that vips_thumbnail will do a better job than some manual processing which maybe outdated after some time.

**Comment by Dynom** [comment]
I've looked into it as well and found at least a couple of issues with the code.

Perhaps unrelated, but there is also a problem with the Crop calculations it seems. However all in all I think it's a good move to lean more on libvips and do fewer tasks in `bimg`. The downside, however, is that we'll be more dependant on libvips in the things they change.

I think that with leaning on [vips_thumbnail_buffer()](http://jcupitt.github.io/libvips/API/current/libvips-resample.html#vips-thumbnail-buffer) more, will make bimg's code quite a bit simpler as well, which would have my preference.

On the other hand, we could leave bimg as low-level and implement these different bindings in Imaginary, since bimg does have a different use-case than Imaginary has. /cc @h2non ?

**Comment by totallyunknown** [comment]
Any updates on this? Just stumbled over this big in my own implementation.

**Comment by totallyunknown** [comment]
I made a PR to fix this. Feedback appreciate.
