### ISSUE TITLE
Black line appears when use fit method

### ISSUE THREAD

**Issue by lastonoga** [h2non/imaginary#249]
Hi @Dynom ,  

There is a problem again with image resize. (fit) #238 

**Original**
![y0gwdzc6e5df3vg3eywevhwl513ulx5mvddusn8m](https://user-images.githubusercontent.com/5420754/52953021-b91ccd80-339f-11e9-83f5-09776666da71.jpg)

**Resized**
![jpeg-1](https://user-images.githubusercontent.com/5420754/52953041-c76ae980-339f-11e9-8de9-24e6680bbd70.jpg)

**Url:**
http://localhost/fit?width=100&height=3000&type=jpeg&url=/media/images/IGhus8SiKg5390WhTrrP6HWeK6Dz3zZLzC9ZHf7B.jpeg

**Comment by Dynom** [comment]
That's not good at all. However afaik there haven't been any changes since the fix to `/fit` in 1.1.18. What version are you on ?

**Comment by lastonoga** [comment]
@Dynom `h2non/imaginary:1.0.18`. Fix that you did, helped with a most images, thanks.
But as you can see some of them have the line. Looks like some problem in algorithm logic. Not only numbers rounding

**Comment by Dynom** [comment]
Alright, I'll look at it once I find the time 👍

**Comment by lastonoga** [comment]
@Dynom Thanks!

**Comment by lastonoga** [comment]
Sorry. URL is http://localhost/fit?width=3000&height=100&type=jpeg&url=/media/images/IGhus8SiKg5390WhTrrP6HWeK6Dz3zZLzC9ZHf7B.jpeg

**Comment by lastonoga** [comment]
#250

**Comment by h2non** [comment]
This should be fixed in `v1.2.0`. Closing for now.
