### ISSUE TITLE
Feature Request - Serve local files.

### ISSUE THREAD

**Issue by Dynom** [h2non/imaginary#25]
Hi,

Currently Imaginary accepts the image content as part of the request, but what if Imaginary runs on the same server where the images are located? It would be useful to add a request parameter with a local location of the file.

e.g.:

    GET /resize HTTP/1.1
    Host: localhost:8088
    file=4fe/5f2/16/foo.jpg&...

and perhaps configure a root directory to make all "path" values relative to this root directory
`./imaginary -mount /mnt/lun01/`

This would apply transitions to the local file `/mnt/lun01/4fe/5f2/16/foo.jpg` and serve it as response.

Updated the feature request to meet the implementation.

**Comment by h2non** [comment]
I agree with the feature. For some scenarios it could indeed very useful. 
Let me think about it in detail, evaluate the best fit and analyze possible security implications.

**Comment by Dynom** [comment]
Awesome, could you give me an update when I'm able to tinker with it?

**Comment by h2non** [comment]
Sure! I wanna do some refactors and cover the feature with some tests before merging to master, however you can test it now switching to `develop` branch.

**Comment by h2non** [comment]
@Dynom this feature is now supported in `master` (0.1.10). 
The usage is pretty simply:
```
imaginary -p 8080 -mount ~/images
```

Now you're able to perform `GET` request specifying the local file name in the mounted directory. E.g:
```
GET /crop?width=200&height=200&file=photo.jpg HTTP/1.1
```

You can also access to nested directory (but not to higher directories for obvious security reasons):
```
GET /crop?width=200&height=200&file=x/y/z/photo.jpg HTTP/1.1
```

The [README](../) was updated as well with this info.
Let me know if you have further questions.

**Comment by Dynom** [comment]
Excellent! I didn't get the branch working with the docker container, but master will work fine. I'll tinker with it today.

Thanks for your time and effort, greatly appreciated!

**Comment by h2non** [comment]
I'll release a new docker tag as well.

Thank you for using imaginary
