### ISSUE TITLE
A strange resutl: 400 Bad Request.

### ISSUE THREAD

**Issue by zhengchun** [h2non/imaginary#252]
Hello, I am got a strange problem, I have a image file at [https://az3.sfo2.digitaloceanspaces.com/dev/1.png](https://az3.sfo2.digitaloceanspaces.com/dev/1.png),it can access and download on the internet. but when i access it via `http://127.0.0.1:9000/thumbnail?height=480&url=https://az3.sfo2.digitaloceanspaces.com/dev/1.png` on my http server it always return `400 Bad Request `. `imaginary` application is running on docker container.

```
Connecting to 127.0.0.1:9000... connected.
HTTP request sent, awaiting response... 400 Bad Request
2019-03-02 13:51:37 ERROR 400: Bad Request.
```

The strange thing is when running above request in my computer(not server) on the docker it can work successful. 

The server request `/` return following result: 
{"imaginary":"1.0.18","bimg":"1.0.18","libvips":"8.7.0"}

**Comment by jbergstroem** [comment]
Pure speculation, but perhaps `ca-certificates` in the container (is it self-baked?) is missing?

**Comment by zhengchun** [comment]
yes, ca-certificates has installed. I'm installed imaginary service from [h2non/imaginary](https://hub.docker.com/r/h2non/imaginary) docker repository. I am using `Nginx` as front-side proxy, and cleaning Nginx cache solve this problem.  Thanks again.
