### ISSUE TITLE
Grey line enlarging image

### ISSUE THREAD

**Issue by barraquito** [h2non/imaginary#261]
A grey line appears in the bottom and right side of the image when I enlarge an JPG image with white background (tested with thumbnail and enlarge method). The bigger I enlarge the image, the most obvious gets the borderline. I'm not sure if it's something related to imaginary or libvips but I couldn't found any information on none of both sites.

Just throw it here to know if this have any known reason that maybe I don't know (yet).

**Comment by Atlantrix** [comment]
Same issue but with black line.
For me it stays at 1 pixel.

**Comment by vposhamod** [comment]
Same issue here - Workaround/hack that removed my black lines: Change from /enlarge to /extract endpoint and assign the areaheight and areawidth queryparams by subtracting 1 pixel from requested height and width appropriately. Using this hack, until this gets fixed.

**Comment by vposhamod** [comment]
Looks like we also have a potential fix in bimg - https://github.com/h2non/bimg/pull/307

**Comment by h2non** [comment]
Fixed in `v1.2.0`. Closing.
