### ISSUE TITLE
icc_import: no input profile

### ISSUE THREAD

**Issue by barnybug** [h2non/imaginary#270]
I'm seeing this error when attempting to resize a jpeg -> webp:
```
{
message: "Error while processing the image: icc_import: no input profile",
code: 1
}
```

Test image here:
http://localhost:9000/resize?url=https://realla-media.s3-eu-west-1.amazonaws.com/test/Channel_digital_image_CMYK_color_noprofile.jpg&width=800&type=webp

Chrome will display the jpeg fine though:
http://localhost:9000/resize?url=https://realla-media.s3-eu-west-1.amazonaws.com/test/Channel_digital_image_CMYK_color_noprofile.jpg&width=800&type=jpeg

The test file I manufactured by removing the profile with `convert +profile "*"` to recreate the issue we are seeing on our actual data.

I appreciate this is probably a poor or bad file format, but is there a way to get imaginary to provide a default icc profile if missing so that we can at least display these images (even if the colourspace is a little off)?

thanks for this great project!

**Comment by h2non** [comment]
Fixed in `v1.2.0`. Closing.
