### ISSUE TITLE
Images with a '+' in the file name are not found

### ISSUE THREAD

**Issue by Atlantrix** [h2non/imaginary#274]
Any image file with a '+' in the file name is not found and that is a problem as for SEO thre are many cases where the + is required in the name.
Ex: A++ for energy class for some products.

Is there a way to go around this bug and keep the + in the filename?

**Comment by h2non** [comment]
You should encode URL unsafe characters properly in order to be decoded later by imaginary. 
Imaginary service is not designed to be SEO optimized. You can always use a proxy layer on top of them or a CDN with paths mapping in order to have more SEO friendly indexable URLs.

Closing.
