### ISSUE TITLE
convert?type=auto causes issues when directly called in browser

### ISSUE THREAD

**Issue by cornedor** [h2non/imaginary#278]
When directly calling convert from the browser I get an error that the type param is not defined. Event tough it is set to auto. Other actions, like resize, don't have that issue and do convert the image to supported formats.

`convert?type=auto&url=https%3A%2F%2Fvia.placeholder.com%2F800x600`:
```json
{"message":"Error while processing the image: Missing required param: type","code":1}
```

This error also results in not returning a `Vary: Accept` header, causing it to be cached with an error.

imaginary: 1.1.1
bimg:  1.0.18
libvips: 8.7.4

**Comment by hipexio** [comment]
We had more or less the same issue and this happens when there is no `Accept` header send. We solved it by adding the header in our cache proxy when it was missing.
