### ISSUE TITLE
EXIF Orientation - Incorrect rotation based on EXIF

### ISSUE THREAD

**Issue by vposhamod** [h2non/imaginary#284]
Hi all,

First of all, thanks for this awesome service.

I think I found an image rotation issue, exif based rotation is not working as expected in case of EXIF values - 2,4, 5 and 7.

Below URLs should all result in the same image, as I'm setting stripmeta to true and norotation to false(default behaviour).

http://localhost:9000/resize?width=300&height=200&url=https://github.com/recurser/exif-orientation-examples/raw/master/Landscape_0.jpg&stripmeta=true

http://localhost:9000/resize?width=300&height=200&url=https://github.com/recurser/exif-orientation-examples/raw/master/Landscape_1.jpg&stripmeta=true

http://localhost:9000/resize?width=300&height=200&url=https://github.com/recurser/exif-orientation-examples/raw/master/Landscape_2.jpg&stripmeta=true

http://localhost:9000/resize?width=300&height=200&url=https://github.com/recurser/exif-orientation-examples/raw/master/Landscape_3.jpg&stripmeta=true

http://localhost:9000/resize?width=300&height=200&url=https://github.com/recurser/exif-orientation-examples/raw/master/Landscape_4.jpg&stripmeta=true

http://localhost:9000/resize?width=300&height=200&url=https://github.com/recurser/exif-orientation-examples/raw/master/Landscape_5.jpg&stripmeta=true

http://localhost:9000/resize?width=300&height=200&url=https://github.com/recurser/exif-orientation-examples/raw/master/Landscape_6.jpg&stripmeta=true

http://localhost:9000/resize?width=300&height=200&url=https://github.com/recurser/exif-orientation-examples/raw/master/Landscape_7.jpg&stripmeta=true

http://localhost:9000/resize?width=300&height=200&url=https://github.com/recurser/exif-orientation-examples/raw/master/Landscape_8.jpg&stripmeta=true

However, responses from Images 2,4,5,7 results in 180 rotated images or flip-flopped images. Please correct me if I missed anything here.

**Comment by h2non** [comment]
Fixed in `v1.2.0`. Closing.
