### ISSUE TITLE
New image on docker

### ISSUE THREAD

**Issue by batiste** [h2non/imaginary#288]
Small request

Is it possible to release a new version on docker hub?

https://hub.docker.com/r/h2non/imaginary/

Cheers and thank you!

**Comment by h2non** [comment]
Dammit, I should have got this automated long time ago in CI. I will try to release a new one tomorrow.

**Comment by batiste** [comment]
Still no luck with a new release? :-)

**Comment by h2non** [comment]
Version `1.1.3` is not on the Docker registry. It has different aliases: `1` and `latest`. Enjoy!
