### ISSUE TITLE
Allow to override HTTP status code.

### ISSUE THREAD

**Issue by giautm** [h2non/imaginary#302]
https://github.com/h2non/imaginary/blob/2b7eb4a0f77870b9a19ba56a08c035db83a76133/error.go#L120

Currently, with `-placeholder` argument. imaginary still return HTTP code from up-stream service/error, that cause some client doesn't load image correct (ex: react-native).

<img width="300" alt="Screen Shot 2020-05-07 at 00 37 02" src="https://user-images.githubusercontent.com/12751435/81209948-5bec5680-8ffb-11ea-868c-fe5890a5047b.png">

If there is an argument to change http code to 200, will be great.

The workaround is override status from proxy nginx.

**Comment by h2non** [comment]
There is no way to configure that at this point but supporting an additional flag to configure this behavior, such as `-placeholder-status=200` can be done. A pull request is welcome.

**Comment by giautm** [comment]
Done, just open a PR. :D

**Comment by h2non** [comment]
Thanks! I will try to launch a new release over the weekend.

**Comment by h2non** [comment]
This feature will be finally available on `v1.2.0` in a few days.
