### ISSUE TITLE
Feature Request: Support for libvips find_trim functionality

### ISSUE THREAD

**Issue by martensievers** [h2non/imaginary#303]
We are using imaginary in a Kubernetes cluster as a public image service but we have ever since been reliant on using services like imgix in addition to this for trimming redundant pixels (especially on png's) as this functionality isn't supported in imaginary as of now.

I have noticed that the latest version of libvips (+8.6) actually has support for image trimming in the form of find_trim() and I was wondering if it would be possible to add support for this functionality to Imaginary too?

PR: https://github.com/libvips/libvips/blob/b9eddecca3185e0ea4804ec48679a0697b17d7d7/libvips/arithmetic/find_trim.c#L70
Website: https://libvips.github.io/libvips/API/current/func-list.html

**Comment by h2non** [comment]
I'm open to support that. A pull request is welcome!

**Comment by martensievers** [comment]
Hi @h2non, I'm unfortunately unfamiliar with GO so I won't be able to help with this but I would appreciate any helping hand that thinks this feature would be nice and could help with the implementation.
