### ISSUE TITLE
Black line appears when use resize method

### ISSUE THREAD

**Issue by pinkiebala** [h2non/imaginary#305]
## Version: `1.1.3`

Maybe related to https://github.com/h2non/imaginary/issues/249

## Original:
url: https://uploads-blog-icook.icook.network/2020/05/59c7b896--%E8%8F%9C%E5%96%AE1080x810.jpg
![original](https://uploads-blog-icook.icook.network/2020/05/59c7b896--%E8%8F%9C%E5%96%AE1080x810.jpg)

## Resized:
url: https://imageproxy.icook.network/resize?height=162&width=216&nocrop=true&url=https%3A%2F%2Fuploads-blog-icook.icook.network%2F2020%2F05%2F59c7b896--%E8%8F%9C%E5%96%AE1080x810.jpg&type=auto
![resized](https://imageproxy.icook.network/resize?height=162&width=216&nocrop=true&url=https%3A%2F%2Fuploads-blog-icook.icook.network%2F2020%2F05%2F59c7b896--%E8%8F%9C%E5%96%AE1080x810.jpg&type=auto)

**Comment by bramvanderholst** [comment]
Currently having the same issue when using 'fit' on v1.1.3

**Comment by stefandoorn** [comment]
Experiencing the same issue on 1.1.3.

**Comment by h2non** [comment]
Fixed in `v1.2.0`. Closing.
