### ISSUE TITLE
Better HTTP status codes on errors?

### ISSUE THREAD

**Issue by mrkurt** [h2non/imaginary#308]
Hello! Imaginary tends to return status 400 for almost everything, which is difficult to work with. Is there a way to make it return:

* 404 if the upstream URL isn't found
* 500 if the operations fail

And less important, but also useful would be:

* 502/503 is upstream times out or is unavailable

**Comment by h2non** [comment]
Feature implemented in `v1.2.0`, now available on the Docker registry under tags: `1.2.0`, `1` & `latest`.
