### ISSUE TITLE
Placeholder Original Size

### ISSUE THREAD

**Issue by 2morales** [h2non/imaginary#319]
Hello everyone, 

I'm having an issue with the placeholder options. I have a custom h2non/imaginary Docker image where I copy an internal image to use as placeholder.

Problem: Whenever I request a resize to imaginary and the image does not exist, the placeholder image comes with the image size I requested instead of the original one.

Is it possible to **always** return the **original size** of the placeholder?

Thanks in advance.

**Comment by h2non** [comment]
The default current behavior is to return the placeholder image matching the requested image size. 
This is the most expected behavior for users as it respects the request contract. 

Are you experiencing any issue with the current behavior?

**Comment by 2morales** [comment]
I'm not experiencing any issue with the current behaviour. 

But is it possible to return (or redirect to a different URL) the original image size?

**Comment by h2non** [comment]
Yes, that could be possible but it's not currently supported. 
I will add this as a feature request for future releases.

**Comment by 2morales** [comment]
Thank you.
