### ISSUE TITLE
TLS/SSL slowness with Debian Buster

### ISSUE THREAD

**Issue by batiste** [h2non/imaginary#331]
We are having massive slowdown from the latest imaginary 1.2.4

Image operation are extra slow, after some investigation this is what I found:

`curl https://storage.googleapis.com/pricehubble-production-pipeline-public/CH/aquaman/images/full/0f1d983c1ca691103062cd1ebe91c18b2c828702.jpg -sS -w "dns_resolution: %{time_namelookup}, tcp_established: %{time_connect}, ssl_handshake_done: %{time_appconnect}, TTFB: %{time_starttransfer}\n" --output somefile`

Gives me:

`dns_resolution: 0.125, tcp_established: 0.126, ssl_handshake_done: **5.200**, TTFB: 5.461`

It seems to be connected with a specific version of debian acording to this thread: https://github.com/curl/curl/issues/3635#issuecomment-469233445

This is the exact same version that are delivered in the current version of imaginary

```
# cat /etc/issue
Ubuntu 16.04.4 LTS \n \l

# curl -V
curl 7.47.0 (x86_64-pc-linux-gnu) libcurl/7.47.0 GnuTLS/3.4.10 zlib/1.2.8 libidn/1.32 librtmp/2.3
```

It would be necessary to fix ASAP. I might give indication on how to do this soon.

**Comment by h2non** [comment]
This does not seem related to `imaginary` or `curl` directly but to GnuTLS library.
Installing `curl` compiled against OpenSSL should solve the issue. 

I'm happy to merge any PR with the Dockerfile fix.

**Comment by batiste** [comment]
Oki so we found out what was the issue. It was our Kubernetes setup.

We gave 10 milli CPU to imaginary with a limit of 20 milli CPU. It is way too small.

At the end we settle for 200m with 500m limit.

Sorry for the noise.
