### ISSUE TITLE
Allowed origin documentation is incorrect

### ISSUE THREAD

**Issue by batiste** [h2non/imaginary#333]
Allowed origin documentation omit the protocol: https://

Without it the server refuse to work properly. The documentation need fixing or the server should accept origin without protocol

created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2962 +0x35c
2020/09/04 11:57:37 http: panic serving 172.17.0.1:49540: runtime error: slice bounds out of range [:2] with length 0

**Comment by h2non** [comment]
PR would be very welcome!

**Comment by batiste** [comment]
This hasn't fixed the problem I believe. I still see this in the doc

--allowed-origins s3.amazonaws.com/some-bucket/

When it should be

--allowed-origins https://s3.amazonaws.com/some-bucket/
