### ISSUE TITLE
Unsupported media type. status :406

### ISSUE THREAD

**Issue by elcanner** [h2non/imaginary#338]
Hi.
Im trying to make a POST but always get Unsupported media type.
There is no example of POST in docs :(

Im trying curl:
curl -X POST "http://localhost:9000/crop?url=https://raw.githubusercontent.com/h2non/imaginary/master/testdata/large.jpg" -d '{"witdh": 180, "height": 180}'

Get request is OK.
curl -vk -o /dev/null "http://localhost:9000/crop?url=https://raw.githubusercontent.com/h2non/imaginary/master/testdata/large.jpg&width=180&heigth=180"

Dont understand how can i make a POST to resize/crop and the most important for me watermarkimage. Is it even possible to POST watermarkimage?

Please add POST exaples to docs.
Thx

**Comment by h2non** [comment]
For URL-based remote image processing, you should only use `GET`.

`POST` method is only intended to be used when uploading an image content (payload data) to the `imaginary` server. E.g: uploading a local disk image that is not accessible via URL somewhere.

**Comment by elcanner** [comment]
got it. Thx.
