### ISSUE TITLE
Detect face to crop and create thumbnail

### ISSUE THREAD

**Issue by cicerocomp** [h2non/imaginary#34]
Link [thumbor](https://github.com/thumbor/thumbor). Implement a Detection Algorithms (https://github.com/thumbor/thumbor/wiki/Detection-algorithms)

**Comment by h2non** [comment]
Thank you! I have also in mind introduce support for smart crop, mostly following this [implementation](https://github.com/jwagner/smartcrop.js).

At this time, you can perform the smart crop calculus using another solution, and then extract the image area using `imaginary`.

**Comment by Dynom** [comment]
I believe the technical term to be Seam Carving or Liquid Rescaling. Just mentioning it here in case people search the issues for it.

I think it would be a great feature to have! But I'm curious, what should happen when no "interesting" center is determined?

**Comment by Dynom** [comment]
There is a Go version of `smartcrop` that seems fairly trivial to add to Imaginary https://github.com/muesli/smartcrop

What is your roadmap on the "smart crop" endeavor @h2non ?

**Comment by h2non** [comment]
The unique bad part I see here is that it depends on OpenCV. I'm not too much open in adding another C dependency which mostly provides the same as `libvips`. 

Some intermediate solutions could be:
- Port the smartcrop from `OpenCV` to `libvips`. Implies considerable non-trivial work.
- Provide a programatic way to, such a middleware/plugin layer, to easily extend behavior related to image processing, adding pre/post processors, extending the standard process pipeline.

**Comment by Dynom** [comment]
So either option requires quite a bit of non-trivial work. What is the strongest argument against linking OpenCV?

**Comment by Dynom** [comment]
@Artyom https://github.com/artyom/smartcrop created a fork without OpenCV dependency!

**Comment by Dynom** [comment]
As of libvips [version 8.5.0](https://github.com/jcupitt/libvips/blob/master/ChangeLog#L61), there is a "smart crop" feature available. It's based on Sharp's smartcrop, which I think is the same as linked earlier here in the Issue.

See also: https://github.com/jcupitt/libvips/blob/c79f64ab7def94b23ca65abf46c4ca9e97e3c5db/libvips/conversion/smartcrop.c

**Comment by Dynom** [comment]
I've made a [PR](https://github.com/h2non/imaginary/pull/136) to implement bimg's smartcrop API. It's obviously not face-detection, but perhaps it's enough for your use-case @cicerocomp ?

**Comment by h2non** [comment]
From `imaginary` v1.0.8+, there is first-class support for smart cropping relying on the built-in [cropping algorithm](https://github.com/jcupitt/libvips/blob/master/libvips/conversion/smartcrop.c) in `libvips`. There is no plans to support face detection in `imaginary`.

For more details, see the documentation:
https://github.com/h2non/imaginary#get--post-smartcrop
