### ISSUE TITLE
Resized images quality

### ISSUE THREAD

**Issue by outlandish** [h2non/imaginary#341]
Hi,

I have an issue with using imaginary for the image resize. 
The problem is resized images are little blurred comparing to the originals, and the less resized size the worse the quality.

I see there was a similar issue in the past: https://github.com/h2non/imaginary/issues/29
I don't quite understand if that behaviour is expected or maybe there is some way or workaround how to fix it.

Here are some examples.

Original:

![cover_original](https://user-images.githubusercontent.com/1417797/101015284-38c95b80-3578-11eb-8891-acb46ee4b53b.jpeg)

Resized:
![cover_m](https://user-images.githubusercontent.com/1417797/101015324-4979d180-3578-11eb-8a3b-5347dd4d5d7c.jpeg)

The request I use for resize: **_/resize?url={imgUrl}&norotation=1&width=768_**

Thank you and will be appreciate any help.

**Comment by outlandish** [comment]
Not relevant anymore

**Comment by rof20004** [comment]
How did you solved that?
