### ISSUE TITLE
SVG support

### ISSUE THREAD

**Issue by robzienert** [h2non/imaginary#36]
My company is on the look out for a microservice that can do image processing for SVGs. bimg does not support SVG, but I'm wondering if you'd be open to abstracting the interaction of image processing of bimg so that we could also use https://github.com/ajstarks/svgo. Thoughts?

**Comment by h2non** [comment]
Ideally this [should be supported](https://github.com/h2non/bimg/issues/61) in `bimg` first. If can't wait, I think the best option is to fork it and perform the required improvements to use another package to specifically process SVG images. The `imaginary` is really simple to extend.

**Comment by h2non** [comment]
SVG suport is now available compiling imaginary against libvips@8.3+ with proper SVG library bindings.

Latest version of imaginary supports SVG image processing.
