### ISSUE TITLE
What causes the "Image Resolution is too Big" Error?

### ISSUE THREAD

**Issue by armouredking** [h2non/imaginary#409]
Hey, so I'm not convinced this is an issue with Imaginary, as I've run the instance before on my own without issue. Per the question on the header though, what could drive this issue? The code seems fairly simple However, trying to research it I wasn't able to find any issues regarding the entry, and my ability to read code leaves a lot to be desired.

The [error.go](https://github.com/h2non/imaginary/blob/master/error.go) file shows ErrResolutionTooBig as a variable on line 27, which seems to be a part of [controllers.go](https://github.com/h2non/imaginary/blob/35c87ba9d5f443b78dd70bfb88a0bac85bf407ab/controllers.go) lines 126-146 but I'm not sure what drives my issue since I didn't encounter it previously running NextCloud / Imaginary in PVE containers. I'm receiving this with the NextCloud AIO instance of Imaginary [#1861](https://github.com/nextcloud/all-in-one/discussions/1861) and I'm unsure if it's a limiting setting or something else.

The log entry in NextCloud is rather simple, and while I do have some big images, again, in the past Imaginary ran without issue (at least, looking in the container's syslog I can see Imaginary working without issue giving 200s for the same "looking" query instead of the 422s AIO is getting) so I want to correct it to what I experienced before (particularly since my hardware can easily support it). Unfortunately, neither the NextCloud log nor syslog entries make a note of which file it's working on.

My previous container on PVE was using go 1.18.3 with a git checkout of cfbf8d724cd326e835dfcb01e7224397c46037d3 for Imaginary.

**Comment by szaimen** [comment]
Will be fixed with https://github.com/nextcloud/all-in-one/pull/1879
