### ISSUE TITLE
High memory after uptime of 3 days and some activity

### ISSUE THREAD

**Issue by Dynom** [h2non/imaginary#42]
Hi,

I notice that currently Imaginary (0.1.14) is consuming quite a bit of memory (even while it's idle)

```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
29688 root      20   0 7483796 6.484g   7304 S   0.0 83.1   1:56.33 imaginary
```

A couple of facts:
* Imaginary current uptime is roughly 3 days
* Imaginary processed (crop action) around 22.000 photos
* Handled around 116.000 requests (all, including health checks)
* Used the `-mount` option, serving around 15.000 unique photos of various sizes ( though mostly >1MiB)
* The health-checks were GET requests to `/form` (although I'm about to reconfigure that to just `/`)
* Imaginary runs in a Docker container, specifying only the `-mount` flag

**Comment by h2non** [comment]
Please, upgrade to  +`0.1.16`. A couple of months ago was introduced a small memory leak in `bimg`, see: https://github.com/h2non/bimg/issues/56.

You can run `benchmark.sh` and try stressing the server for a while (> 1 min) and see how the RSS memory is flushed over the time.

**Comment by h2non** [comment]
I did a benchmark suite stressing the server during 6 minutes with a concurrency of `30` req/sec while cropping a JPEG image of 900KB.

The RSS memory is stable, always under 160MB. Here're the results:
```
Requests	[total]				10800
Duration	[total, attack, wait]		6m0.068820053s, 5m59.966785955s, 102.034098ms
Latencies	[mean, 50, 95, 99, max]		113.507773ms, 111.361526ms, 133.969045ms, 175.520796ms, 256.97102ms
Bytes In	[total, mean]			1265965200, 117219.00
Bytes Out	[total, mean]			9477918000, 877585.00
Success		[ratio]				100.00%
Status Codes	[code:count]			200:10800  
Error Set:
```

**Comment by Dynom** [comment]
Excellent, I'll schedule the update in our next deployment. I was hoping this was already fixed (-:

**Comment by h2non** [comment]
@Dynom FYI I have just provided support for `/health` endpoint, so you can check it to retrieve useful information about the server and runtime stats.

See the [docs](https://github.com/h2non/imaginary#get-health) for more info.

**Comment by Dynom** [comment]
Ah excellent, I was just thinking about adding such a feature! It's like you read my mind @h2non ;-)
