### ISSUE TITLE
Do we have any server side caching machanisam in imaginary ?

### ISSUE THREAD

**Issue by macpatel** [h2non/imaginary#48]
I was trying [picfit](https://github.com/thoas/picfit) and imaginary.
One thing that picfit lacks is the less option for playing with your images. Specially crop.
Imaginary lacks server side caching of images which are converted by imaginary in past requests. 

Do you guyz have any alternative for server side caching with imaginary ?

**Comment by h2non** [comment]
Image caching responsibilities are outside of the scope of the project. [Read this](https://github.com/h2non/imaginary/issues/33#issuecomment-151224065) for further information.
