### ISSUE TITLE
Resizing width is set based on rotated image dimensions

### ISSUE THREAD

**Issue by kylechadha** [h2non/imaginary#50]
I have this raw image: https://printio-widget-live.s3.amazonaws.com/1B08580D-ABB9-4848-BB96-5D2DCFCD5BFC.jpeg, which is 4000x6000.

I pass it to our resizer with a width of 1000 set: http://pio-image-resizer.elasticbeanstalk.com/resize?width=1000&url=https://printio-widget-live.s3.amazonaws.com/1B08580D-ABB9-4848-BB96-5D2DCFCD5BFC.jpeg

It returns an image that is 667x666, instead of one that is 1000x1500.

Adding `norotation=true`, I see that it's calculating the width based on the unrotated image, resizing it, and then rotating it. Which is resulting in a cropped, square image.

Is this a bug? Are there other options I can use to get around this? Thanks.

**Comment by h2non** [comment]
What about this?:
http://pio-image-resizer.elasticbeanstalk.com/resize?width=1000&height=1000&force=true&url=https://printio-widget-live.s3.amazonaws.com/1B08580D-ABB9-4848-BB96-5D2DCFCD5BFC.jpeg

**Comment by h2non** [comment]
I guess this is what you're looking for:
http://pio-image-resizer.elasticbeanstalk.com/resize?height=1000&force=true&noautorotate=true&url=https://printio-widget-live.s3.amazonaws.com/1B08580D-ABB9-4848-BB96-5D2DCFCD5BFC.jpeg

**Comment by h2non** [comment]
`imaginary`, via `bimg`, tries to provide the most common and default behavior while processing images, that means in this case perform some default calculations and image transformations.

If you want another more specific behavior, you should enable it explicitly. This is not a bug. If the supported params are not enough, feel free to share what you really need and perhaps it might be easily supported.

**Comment by kylechadha** [comment]
Unfortunately neither of those are what I'm looking for. I want the 4000x6000 image to be resized with a width of 1000, without its orientation or anything else changing. I played with the options and it seems like there's no combination that can achieve this. 

Shouldn't the default behavior for an image with `width=1000` specified be that the image is indeed resized to a width of 1000px?

**Comment by h2non** [comment]
You can actually resize it to the desired width: 
http://pio-image-resizer.elasticbeanstalk.com/resize?width=1000&force=true&url=https://printio-widget-live.s3.amazonaws.com/1B08580D-ABB9-4848-BB96-5D2DCFCD5BFC.jpeg

Result: no default cropping, width is 1000px and height is maintained.

**Comment by kylechadha** [comment]
The height isn't maintained though: it becomes 666px, when it should be 1500px.

This is the image I would expect to see: http://pio-image-resizer.elasticbeanstalk.com/resize?width=1000&height=1500&url=https://printio-widget-live.s3.amazonaws.com/1B08580D-ABB9-4848-BB96-5D2DCFCD5BFC.jpeg

**Comment by h2non** [comment]
I believe that an additional calculus is required to process that kind of image where the ratio is no the usual to resize it properly taking into account both axis.

Feel free to test and dig into [the code](https://github.com/h2non/bimg/blob/master/resize.go) to support what you're looking for. I'm fully open to PR.

**Comment by kylechadha** [comment]
Hrm, I'm still a bit confused. What's unusual about the ratio? If the params specify width=1000, shouldn't the image returned have a width of 1000?

**Comment by h2non** [comment]
Yes, but what about the height? Should it remain as 6000px? 
IMHO it should be inferred based on the image resolution to maintain the original ratio.

When I've time I'll perform some more accurated tests in other to handle that kind of images in multiple transformation, but feel free to go ahead if you need it.

I agree about the crop calculus in this case in not effective and should be improved.

**Comment by h2non** [comment]
Actually there's a minor issue with crop calculus based on the target size and image size. If you try with different resolutions you can reproduce the issue:

Works as expected:
http://pio-image-resizer.elasticbeanstalk.com/resize?width=1200&noautorotate=true&url=https://printio-widget-live.s3.amazonaws.com/1B08580D-ABB9-4848-BB96-5D2DCFCD5BFC.jpeg

Other resolutions:
- 1400
- 1600
- 1160

Doesn't works:
http://pio-image-resizer.elasticbeanstalk.com/resize?width=1000&noautorotate=true&url=https://printio-widget-live.s3.amazonaws.com/1B08580D-ABB9-4848-BB96-5D2DCFCD5BFC.jpeg

Other resolutions:
- 1111
- 1333

I've to dig into dig when I've time.

**Comment by kylechadha** [comment]
Okay, thanks @h2non. I'll also take a look at the source or see if I can come up with a workaround. It seems to me that the rotation should be applied first before anything else is calculated.

**Comment by kylechadha** [comment]
Btw -- from an end user's perspective this is the approach that makes the most sense to me:
> IMHO it should be inferred based on the image resolution to maintain the original ratio.

**Comment by h2non** [comment]
Sorry about the silence here. I'm pushing a new project to production early these days, so I was so busy in the last months.

When I'm definitely free I'll fix the issue in `bimg`.

**Comment by h2non** [comment]
I had time to invest digging into this, finally. The issue was related to the EXIF orientation. I've tried with different images with same size and everything was fine. [I've fixed](https://github.com/h2non/bimg/commit/b198ea2ecc6eeafa5e70a7394a2139ea3f6fb9b6) this in `bimg`.

I've just released `imaginary` 0.1.19 with the fix.
