### ISSUE TITLE
Cloud foundry support

### ISSUE THREAD

**Issue by el-davo** [h2non/imaginary#51]
Hi

I am wondering do you have any plans to add Pivotal cloud foundry support to this library.All our microservices are deployed to a private cloud foundry instance and it would be amazing if I could easily deploy this to the same architecture. I had some luck updating the imaginary buildpack to work and it deploys correctly but crashes when it tries to run (Not sure why)

If you could let me know if their are any plans for this or if this is already done that would be awesome

*NOTE* I forked the repo here and updated this file - https://github.com/el-davo/heroku-buildpack-imaginary/blob/master/bin/compile

*NOTE* This is probably not very helpful but this is the error i get from cloud foundry

Tue Jan 05 2016 15:33:26 GMT+0000 (GMT Standard Time) [DEA] ERR Instance (index 0) failed to start accepting connections
Tue Jan 05 2016 15:33:26 GMT+0000 (GMT Standard Time) [API] OUT App instance exited with guid f832b295-76c3-4813-b78a-3dc9b87edbab payload: {"cc_partition"=>"default", "droplet"=>"f832b295-76c3-4813-b78a-3dc9b87edbab", "version"=>"f0cd20b5-1685-49a5-8655-436cc801d0b5", "instance"=>"d27ebe59c19e4c54af51b02757fe021f", "index"=>0, "reason"=>"CRASHED", "exit_status"=>127, "exit_description"=>"failed to accept connections within health check timeout", "crash_timestamp"=>1452008006}

Not very useful :(

Thanks,
Dave

**Comment by h2non** [comment]
Neved used Cloud Foundry, but seems like it's moslty compatible or based on Heroku PaaS.
I would recommend you fork and extend the [Go buildpack](https://github.com/cloudfoundry/go-buildpack) with the [libvips installation](https://github.com/cloudfoundry/go-buildpack). I think it would be easier for your. 

Personally, I don't have plans to support any other provider, but I'm open to PRs.

**Comment by el-davo** [comment]
Thanks for the quick response. 

I will look into your suggestion

**Comment by h2non** [comment]
I think we can close this. Feel free to open a PR if you create something related to Cloud Foundry and want to share it here.

**Comment by el-davo** [comment]
Hi

Yep you can close 

We have decided to wait for cloud foundry 1.6, which has docker support out of the box. We should then in theory be able to use the docker image you have provided.

Hopefully that should work for us. If not I will continue to investigate the buildpack route :)
