### ISSUE TITLE
Tutorial for using POST?

### ISSUE THREAD

**Issue by y22ma** [h2non/imaginary#65]
Hi,

Thanks for the great work. Just wondering if I can send imaginary server an image using POST? If so, is it possible to add an example to README usage section?

Cheers,

**Comment by y22ma** [comment]
Found out how after a certain about of fudging around. This is the command I used to take an image from my Desktop, pushed to imaginary and got a processed image back.

curl   -F "file=@/home/user/Desktop/pic.png" "http://localhost:8080/resize?width=300&height=200&type=jpeg" > pic_resized.jpg

**Comment by h2non** [comment]
It's briefly explained here: https://github.com/h2non/imaginary#form-data

Basically, you can do POST requests sending the image as `multipart/form-data` with one file field called `file` or sending the raw buffer as `image/jpeg`/`image/png`.

You can also see an imaginary client implementation here:
https://github.com/h2non/node-imaginary
