### ISSUE TITLE
Resize and flip in one request

### ISSUE THREAD

**Issue by benone** [h2non/imaginary#66]
Can I do resize and flip in one request?

**Comment by h2non** [comment]
You can resize and rotate by refining the specific dregrees in a single request. Just define the rotate query param.

**Comment by benone** [comment]
Thank you! But can I resize and flip in one request too?

**Comment by h2non** [comment]
[Now](https://github.com/h2non/imaginary/pull/70) you [can](https://github.com/h2non/imaginary/releases/tag/0.1.23). 

Example: `http://your-imaginary-server:8088/resize?width=500&flip=true`
Same goes for `flop`: `http://your-imaginary-server:8088/resize?width=500&flop=true`

Update `imaginary`: `go get -u github.com/h2non/imaginary`

Enjoy.
