### ISSUE TITLE
Choose background color when converting transparent PNG to JPEG

### ISSUE THREAD

**Issue by Algae666** [h2non/imaginary#68]
When converting transparent PNGs to JPEG (http://localhost:8080/convert?type=jpeg&file=test.png), the transparent parts of the JPEG will get converted to black, but I would like to have them match the background that I am displaying them on (in this case, white). With ImageMagick, you'd just set the background color to white and flatten the PNG when you convert it, but I can't find any such option in the imaginary API.

**Comment by Algae666** [comment]
Looking into bimg a bit, it looks like the options have a background, and if it's set to other than black, it will do a flatten, so it seems that only the API needs to be modified to add background as a parameter!

**Comment by Algae666** [comment]
Got it to work with just a couple of tweaks to params.go and options.go... yay!

**Comment by h2non** [comment]
Feel free to share the code or send a PR.

**Comment by Algae666** [comment]
Hey Tomás,

Here's the code I modified:



But it doesn't seem to work for all images. Here's an example of one that fails:

and here's the error message that it gives me:

{"message":"Error while processing the image: linear: vector must have 1 or 2 elements","code":1}

I though it may be because the PNG has no alpha channel, so I tried modifying the bimg resize class to check for that, but I may not have done it right, because I still get the error.



Thanks!
Alan

**Comment by Algae666** [comment]
Just figured out the I wasn't getting bimg to install correctly, but I can accomplish the same thing by modifying image.go with the following (at the end of both the Resize and Convert functions):

	meta, err := bimg.Metadata(buf)
	if err == nil && meta.Alpha && len(o.Background)>2 {
		opts.Background = bimg.Color{o.Background[0],o.Background[1],o.Background[2]}
	}
	return Process(buf, opts)

This works for both alpha and non-alpha PNGs

**Comment by h2non** [comment]
Your changes are now in master. I will release a new version in Docker as well one of these days.

Feel free to close this issue if there's nothing more to add here.
