### ISSUE TITLE
Does this support progressive images? Or how can it be added?

### ISSUE THREAD

**Issue by SharadKumar** [h2non/imaginary#76]
It will really help to know how can I implement that, as I like that fact that you have a buildpack and a node client.

**Comment by h2non** [comment]
Progressive image rendering is not supported by limitation on `libvips`. 
See: https://github.com/jcupitt/libvips/issues/77

As workaround (but with some server-side performance cost) I'd suggest to use the Go's [image](https://golang.org/pkg/image/) built-in package to transform the `libvips` original image into a progressive image and then serve it via HTTP.

If you can provide a solid enough solution and you don't mind creating a PR for it, with some proper test cases, I would not mind adding it as part of `imaginary` as optional activatable feature.

**Comment by SharadKumar** [comment]
Hi @h2non I switched to `sharp` for now. 
https://github.com/asilvas/node-image-steam

@asilvas

**Comment by SharadKumar** [comment]
Sharp has pretty good performance! So it seems to be working for us.
http://sharp.dimens.io/en/stable/performance/

@lovell

**Comment by h2non** [comment]
Great.
