### ISSUE TITLE
Issue when run docker container: 9000: bind: address already in use

### ISSUE THREAD

**Issue by dario-santandrea** [h2non/imaginary#87]
Hi i'm trying to run imaginary on Docker and i have one issue when try to run the server:

**cannot start the server: [listen tcp :9000: bind: address already in use]**

the steps followed are:

1)
docker run -d -p 9000:9000 --name imaginary h2non/imaginary:latest -cors -gzip

2) 
docker exec -it imaginary bash

3)
/go# imaginary -p 80

4)
cannot start the server: [listen tcp :9000: bind: address already in use]

I tried to run the container in others ports like 9001:9000, 9002:9002 but always get the same error.

Any idea?

Regards.

**Comment by h2non** [comment]
You're running the container in `daemon` mode, which basically means running it in background. You should stop the running containers that are binding network connection to that port before start the container, or change the port number. You can do that in two ways:

Via environment variable:
```bash
docker run -p 9000:9000 -e PORT=9000 h2non/imaginary:latest -cors -gzip
```

Via CLI flag:
```bash
docker run -p 9000:9000 --name imaginary h2non/imaginary:latest -cors -gzip -p 9000
```
