### ISSUE TITLE
Support custom fill color for nocrop=true on JPEG resize

### ISSUE THREAD

**Issue by tipsytopsy** [h2non/imaginary#92]
Hi there,

Is there any way I can specify a custom color for fill color when nocrop is set to true on jpeg resize? Currently it defaults to black, I would like to change to white (or configurable). I can create a PR to support that, but could you please guide me where to look at? (I'm a java guy, but will try my hand at Go).

Thanks!

**Comment by h2non** [comment]
That's already supported using the `background` query param, such as:
```bash
?background=250,20,10
```

See all the available query params here:
https://github.com/h2non/imaginary#params

**Comment by tipsytopsy** [comment]
Hmm.. It didn't work in combination with nocrop. I may have done something
wrong, will try again and report back. Thanks!

**Comment by tipsytopsy** [comment]
No idea what is going on my machine or my head. It worked initially - and cannot get it working now. No idea where the cache is or the issue it.

width=200&height=200&nocrop=true&background=255,255,255 is giving this result:

https://snag.gy/JvnLVN.jpg

And I'm sure it worked for me previously.

**Comment by tipsytopsy** [comment]
Now I know. It works for PNG and not for JPEG. This is the image info for PNG which works:
{
  "width": 1403,
  "height": 841,
  "type": "png",
  "space": "srgb",
  "hasAlpha": true,
  "hasProfile": false,
  "channels": 4,
  "orientation": 0
}

This is image info for JPEG which does not work with background:
{
  "width": 815,
  "height": 417,
  "type": "jpeg",
  "space": "srgb",
  "hasAlpha": false,
  "hasProfile": true,
  "channels": 3,
  "orientation": 0
}

**Comment by h2non** [comment]
Yes, non-PNG images do not support background.

**Comment by h2non** [comment]
`nocrop=true` has no side-effects with the background processing.

You can try with:
```
/resize?width=300&height=200&nocrop=true&background=200,100,50&type=jpeg&url=http://i0.wp.com/freepngimages.com/wp-content/uploads/2015/11/bald-head-transparent-background.png?fit=300%2C300
```

Also, please update `imaginary` to latest version, some improvements has been introduced recently:
```bash
go get -u github.com/h2non/imaginary
```

**Comment by tipsytopsy** [comment]
Thank you @h2non ! I'm currently using 0.1.26 docker image. I'll update to 0.1.27 to see if the issue is fixed.

In the test URL you gave - the source is PNG so it works fine. But when I use a JPEG source - the fill color on resize defaults to black and cannot be changed? Is there anywhere in bimg/ imaginary I could possibly hardcode temporarily to use a different fill-color? The use case of this image would be to show in a fix dimension box - so a black bar will not look good and we'll need JPEG support since most of the images are JPEGs.

Could you advice if I could potentially fix for short term in a fork?

Thanks!

**Comment by h2non** [comment]
You can process the image via libvips in do amy pixel/color schema transformation you want, such as replacing each pixel by color, but that's is too domain specific and won't be suported in bimg/imaginary, as they are generic solutions.

You should probably read libvips documentation and examples to see how to do that properly.

**Comment by tipsytopsy** [comment]
Thanks. Since libvips is putting the pad/fill as black when resizing JPEGs, it should be using the the default values from somewhere? Is there anyway I can add those values in bimg (in my own fork)? This is the only missing thing I need in this otherwise awesome lib.

**Comment by tipsytopsy** [comment]
@h2non  - I was able to temporarily fix the JPEG resize issue by using the correct extend value. Change can be seen here: [https://github.com/h2non/bimg/compare/master...tipsytopsy:master](https://github.com/h2non/bimg/compare/master...tipsytopsy:master).

I think this is a bug since I don't see the Extend option being set. Anyway this fix removes a blocker for me. There is another non-blocker issue on enlarge where png transparency is converted to black when output type is jpeg. But we can live with it by using png->png and jpeg->jpeg. I'll try to find out what enhancement is needed to pass the correct background flag to libvips for enlarge.

**Comment by h2non** [comment]
I've support this properly in this PR: https://github.com/h2non/bimg/pull/115

Let me know if that fits what you're looking for.

**Comment by tipsytopsy** [comment]
Perfect! This looks like a clean solution. Looking forward for this going
to master.
