### ISSUE TITLE
Getting error while testing watermark API from the form page

### ISSUE THREAD

**Issue by sachinwalia2k8** [h2non/imaginary#96]
I am uploading a 10 KB png to this URL

`http://localhost:8888/watermark?textwidth=100&text=Hello&font=sans%2012&opacity=0.5&color=255,200,50
`
This is the error generated on the browser:

`{"message":"Error while processing the image: VipsOperation: class \"text\" not found","code":1}
`
FYI this is the version information by hitting: http://localhost:8888

`{"imaginary":"0.1.27","bimg":"1.0.4","libvips":"8.3.3"}
`

**Comment by h2non** [comment]
Your `libvips` compilation does not support watermark text processing. 
You should install and compile `libvips` again linking against the required libraries.
See the installation script for reference.

**Comment by sachinwalia2k8** [comment]
Thanks. I am going to try it. I believe libvips requires pangoft2 for text rendering to work?

**Comment by h2non** [comment]
Yes, libpango to be more specific.

**Comment by h2non** [comment]
Question has been resolved. Closing for now.
